# fly.toml app configuration file generated for vaultwarden-mc on 2026-06-10T21:23:40+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

primary_region = 'lhr'

[build]

[env]
SIGNUPS_ALLOWED = "false"
INVITATIONS_ALLOWED = "false"
SHOW_PASSWORD_HINT = "false"


[[mounts]]
source = 'vw_data'
destination = '/data'
initial_size = '1gb'
auto_extend_size_threshold = 80
auto_extend_size_increment = '1gb'
auto_extend_size_limit = '10gb'

[http_service]
internal_port = 80
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
memory_mb = 512
